# Generated by Django 3.1.6 on 2021-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='perice',
            new_name='price',
        ),
    ]
