# Generated by Django 3.1.6 on 2021-05-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210409_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='profile', verbose_name='الصورة الشخصية'),
            preserve_default=False,
        ),
    ]
