# Generated by Django 3.1.6 on 2021-07-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210724_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hour_of_wait',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hour_of_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد سعات العمل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر المكالمة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=1000, verbose_name='من انا'),
        ),
    ]
