# Generated by Django 3.1.6 on 2021-08-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='namedoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
